### PR TITLE
T369636: Fix border misalignment

### PR DESCRIPTION
**Pull request by medied**
https://phabricator.wikimedia.org/T369636

Follow up to #134. [QA feedback pointed](https://phabricator.wikimedia.org/T369636#10310286) to some weird rendering in the corners, after looking very closely I think indeed this `border-radius` is messing with the correct border rendering. 

You really need to get your magnifying glass out to see this one, but I believe this is what was caught by QA:

| with border-radius | without border-radius |
|--------|-------|
| Before Image | After Image |
| Before Image | After Image |

### CODE REVIEW

**Comment by medied** [comment]
From phab description:
> In darkmode, some whitespace is visible at the bottom of the preview

@stephanebisson can you still replicate the above with this branch? If so, could you please provide a screenshot for clarity?

**Comment by medied** [comment]
CI error seems to be related to npm, it's failing to complete the install and build step. Searching online recommends running `npm cache clean --force` which I'm trying in https://github.com/wikimedia/wikipediapreview-wordpress/pull/135/commits/96b00b60de1231660dffbad6b0693d892bcb0e12 but no luck yet. I can run `npm install` and `npm build` commands locally without an issue 🤔

**Comment by Nikerabbit** [comment]
This is likely https://github.com/webpack/webpack/issues/18963 / https://github.com/nodejs/node/issues/55826

**Comment by medied** [comment]
> This is likely [webpack/webpack#18963](https://github.com/webpack/webpack/issues/18963) / [nodejs/node#55826](https://github.com/nodejs/node/issues/55826)

Thanks, specified a working version for now. Once the webpack issue is resolved, we can revert back to using latest node. I'm subscribed to the ticket

**Comment by stephanebisson** [comment]
Great! I'll go ahead and merge this. 

Could you open a new PR right away that sets the node version back to 'latest' so we can merge it when it passes.

**Comment by medied** [comment]
> Could you open a new PR right away that sets the node version back to 'latest' so we can merge it when it passes.

Done 👆

**Pull request merged**
