### PR TITLE
Missing step of package.json during version.sh script

### PR DESCRIPTION
**Pull request by hueitan**
The version in package-lock.json also need to update, then stage the package.json and package-lock.json files.

### CODE REVIEW

**Comment by medied** [comment]
What happens exactly if we don't stage package.json and package-lock.json? I remember seeing a package-lock.json out of line in my set up once in between changing branches, sounds like this was the reason

**Comment by hueitan** [comment]
> git add those files so they are included in the version update commit.

When running `npm run version`, we make sure every place has the same version number.

**Review by medied — APPROVED** [review]

**Comment by stephanebisson** [comment]
> When running `npm run version`, we make sure every place has the same version number.

You shouln't do `npm run version`.

The `version` action is a hook that runs when we do `npm version patch|minor|major` to up the version number. It takes care of creating a new commit with the package and package lock files.

**Comment by hueitan** [comment]
TIL 👍 thanks for sharing the info @stephanebisson

**Pull request closed without merging**
